src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $deadline;

    /**
     * @ORM\ManyToOne(targetEntity=Project::class, inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $projet;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(\DateTimeInterface $deadline): self
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getProjet(): ?Project
    {
        return $this->projet;
    }

    public function setProjet(?Project $projet): self
    {
        $this->projet = $projet;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('name', TextType::class, array(
            'label' => 'Nom de la tâche',
        ))
            ->add('description')
            ->add('deadline' , DateType::class, [
                'input'  => 'datetime'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\ProjectRepository;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/task')]
class TaskController extends AbstractController
{
    #[Route('/', name: 'task_index', methods: ['GET'])]
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('task/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }
  
    #[Route('/new/{projectId}', name: 'task_new', methods: ['GET', 'POST'])]

    public function new(Request $request, ProjectRepository $ProjectRepository, int $projectId): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $project =$ProjectRepository->find($projectId);
            $task->setDateCreation(new \DateTime());
            $task->setProjet($project);
            $task->setStatus('En cours');
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('project_show', ['id' => $projectId], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('task/new.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'task_show', methods: ['GET'])]
    public function show(Task $task): Response
    {
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    #[Route('/{id}/edit', name: 'task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/deleteTask', name: 'task_delete', methods: ['GET','POST'])]


    public function delete(int $id=1, TaskRepository $TaskRepository): Response
    {
        
            $Task = $TaskRepository->find($id);
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($Task);
            $entityManager->flush();
       
            return $this->redirectToRoute('project_show', ['id' => $Task->getProjet()->getId()], Response::HTTP_SEE_OTHER);
            
    }


    #[Route('/{id}/updateStatus', name: 'status_update', methods: ['GET','POST'])]
    public function statusUpdate(int $id=1, TaskRepository $TaskRepository): Response
    {
        
            $Task = $TaskRepository->find($id);
            $Task->setStatus("Terminé");
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Task);
            $entityManager->flush();
       
        return $this->redirectToRoute('project_show', ['id' => $Task->getProjet()->getId()], Response::HTTP_SEE_OTHER);
            
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning">{{ button_label|default('Ajouter la tâche') }}</button>
{{ form_end(form) }}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('task_index') }}">back to list</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}
    <h1>Task index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date_creation</th>
                <th>Deadline</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.name }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.dateCreation ? task.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ task.deadline ? task.deadline|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('task_show', {'id': task.id}) }}">show</a>
                    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('task_new') }}">Create new</a>
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle tâche{% endblock %}

{% block body %}
    <h1>Nouvelle tâche</h1>

    {{ include('task/_form.html.twig') }}

    <a class="btn btn-warning my-3" href="{{ path('project_index') }}">Retour à l'accueil</a>
{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ task.description }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ task.dateCreation ? task.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deadline</th>
                <td>{{ task.deadline ? task.deadline|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('task_index') }}">back to list</a>

    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}